google-sargo: move openrc gnss service to openrc subpackage
On a new installation, the OpenRC subpackage can be installed before the
main package. The modem-gnss service is already needed when the
subpackage is installed. Move the service file to the subpackage so new
installations don't error out.

    ( 66/750) Installing device-google-sargo-openrc (13-r0)
    device-google-sargo-openrc-13-r0.post-install: Executing script...
    device-google-sargo-openrc-13-r0.post-install:  * service hexagonrpcd-adsp-sensorspd added to runlevel sysinit
    device-google-sargo-openrc-13-r0.post-install:  * rc-update: service `modem-gnss' does not exist
    ERROR: device-google-sargo-openrc-13-r0.post-install: exited with error 1
    ...
    (199/750) Installing device-google-sargo (13-r0)
    ...
    1 error; 1335 MiB in 766 packages

Link: https://builds.sr.ht/~postmarketos/job/1542762#task-img

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6866