Revert "main/postmarketos-ui-console: do not install any audio backend by default (MR 6192)"
This reverts commit e2557598d71acc8a37fc70b14f9ec61fff2d7fff. The patch
caused installs to fail where the device package explicitly depends on
postmarketos-base-ui-audio-pipewire:

ERROR: unable to select packages:
  postmarketos-base-ui-audio-pipewire-35-r0:
    conflicts: postmarketos-base-ui-audio-none-35-r0[postmarketos-base-ui-audio=35-r0]
    satisfies: device-xiaomi-nabu-5-r0[postmarketos-base-ui-audio-pipewire]
               postmarketos-base-ui-35-r0[postmarketos-base-ui-audio]
  postmarketos-base-ui-audio-none-35-r0:
    conflicts: postmarketos-base-ui-audio-pipewire-35-r0[postmarketos-base-ui-audio=35-r0]
    satisfies: world[postmarketos-base-ui-audio-none]
               postmarketos-base-ui-35-r0[postmarketos-base-ui-audio]

I've also tried to move the postmarketos-base-ui-audio-pipewire
dependency into a subpackage that doesn't get installed when
postmarketos-ui-console gets installed. But that did *not* work:

audio() {
	# This does NOT work!
	install_if="$pkgname=$pkgver-r$pkgrel postmarketos-base-ui !postmarketos-ui-console"
	mkdir "$subpkgdir"
}

It could work if postmarketos-ui-console did not depend on
postmarketos-base-ui, maybe that should be looked at in a follow-up
patch. Or just install the audio stack and require the user to do
UI=none if they want a really minimal system. Let's revert the patch now
to fix failing installs in bpo, e.g. master:xiaomi-nabu:console.

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6408