nokia-n900: move wl1251-cal-openrc dep to openrc
Fix master:nokia-n900:console, which is failing since the console UI was
switched to systemd by default:

  (66/230) Installing wl1251-cal-openrc (1.2-r4)
  Executing wl1251-cal-openrc-1.2-r4.post-install
  lib/apk/exec/wl1251-cal-openrc-1.2-r4.post-install: line 3: rc-update: not found
  ERROR: wl1251-cal-openrc-1.2-r4.post-install: script exited with error 127

Related: https://builds.sr.ht/~postmarketos/job/1474072#task-img-730

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6436